### ISSUE TITLE
Drawer 抽屉展开时出现严重掉帧问题

### ISSUE THREAD

**Issue by fython** [JuniperPhoton/MyerSplashAndroid#1]
当列表滚到顶部两三张图时还不会出现这种状况，但滚动到后面停顿下来后 Drawer 展开时会出现较严重的卡顿，暂没有去分析原因。

报告机型：OnePlus One
系统：(AOSP) Android 7.0

**Comment by JuniperPhoton** [comment]
这种问题...唔似乎 MyerList 在坚果手机上遇到过；当 Drawer 卡的时候，点击图片进入详情的动画也卡顿么？

**Comment by fython** [comment]
进入详情的动画没有卡顿
